# Site settings
title: Smoke Cease
email: your-email@domain.com
description: "I gotta quit, i just need a little help"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://smokecease.com" # the base hostname & protocol for your site
twitter_username: smokecease
github_username:  smokecease

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
